using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SpaceShooter
{
    public class LevelBoundaryLimited : MonoBehaviour
    {
        private void Update()
        {
            if (LevelBoundary.Instance == null) return;

            var lb = LevelBoundary.Instance;
            var r = LevelBoundary.Instance.Radius;

            if(transform.position.magnitude>r)
            {
                if(lb.LimitMode==LevelBoundary.Mode.Limit)
                {
                    transform.position = transform.position.normalized * r;
                }

                if(lb.LimitMode== LevelBoundary.Mode.Teleport)
                {
                    transform.position = -transform.position.normalized * r;
                }
            }
        }
    }
}